fix(data-input): In date column filter "current date" option is not working ( XPS-18387 ).
visualbis/react-querybuilder pull request #72
Opened 2023-01-31 08:03 UTC by vichu5101

2023-02-01 14:33 UTC, ArulValan requested changes

2023-02-01 14:33 UTC, ArulValan commented on src/controls/ValueEditor.tsx
> +        onSelectDateChange: onSelectDateChange,
```suggestion
        onSelectDateChange,
```

2023-02-01 14:33 UTC, ArulValan commented on src/controls/ValueEditor.tsx
> +      setTodayDate(false);
Shouldn't we check other the date is today's before setting it to false

2023-02-01 14:34 UTC, ArulValan requested changes
Please fix these two issues

2023-02-02 06:12 UTC, ArulValan approved these changes

2023-02-13 03:54 UTC, vbiarulkumar approved these changes

2023-02-14 05:32 UTC, merged